name: Deploy to GH Pages

on:
  push:
    branches:
      - react
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          browser: chrome

      - name: Upload test screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build
