name: Deploy to GH Pages

on:
  push:
    branches:
      - react
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Run Chrome tests
        uses: cypress-io/github-action@v3
        with:
          start: npm run production
          wait-on: 'http://localhost:3000'
          browser: chrome

      - name: Run Firefox tests
        uses: cypress-io/github-action@v3
        with:
          start: npm run production
          wait-on: 'http://localhost:3000'
          browser: firefox

      - name: Upload test screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build
